Style/Documentation:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

PerlBackrefs:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
